apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: instavote-dev
  namespace: argocd
spec:
  description: Development environment for Instavote application
  sourceRepos:
    - '*'
  destinations:
    - namespace: instavote-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
